### ISSUE TITLE
How to get the correct sequence of words after apply OCR?

### ISSUE THREAD

**Issue by Mohammed91** [Vikrant-Deshmukh/Scene-Text-Recognition-OpenCV#1]
@Vikrant-Deshmukh  
Dear Vikrant,
it is good project, but how i can print the correct sequence of words that match in image. because in this project when i print text after apply OCR... the sequence of words that printed not match the sequence of words in the image.
Thank You

**Comment by Vikrant-Deshmukh** [comment]
Hello Mohammed, I am not working on this project as of now. Once I get the time I will resolve the issue and update the code.

**Comment by Mohammed91** [comment]
Thank you very much Mr. Vikrant.
